version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_DATABASE: riyaoeiu_xdatuyh
      MYSQL_ROOT_PASSWORD: nQ~YWEKH6g*3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
